---
# tasks file for roles/rollbacksvc
######################################################
# 1. 방화벽 포트 제거:
#     - http
#     - https
# 2. 서비스 종료:
#     - httpd
#     - firewalld
# 3. 웹 서비스 설정 삭제
#     - /etc/httpd/conf.d/vhost.conf
#     - /var/www/html/index.html
#     - /var/www/vhosts
# 4. 패키지 삭제
#     - httpd
#     - mod_ssl
######################################################
- name: 1. 방화벽 포트 제거
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: disabled
  loop: "{{ fw_rules }}"
  ignore_errors: true

- name: 2. 서비스 종료
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    enabled: false
  loop: "{{ svcs }}"


- name: 웹 서비스 설정 파일 삭제
  ansible.builtin.file:
    name: "{{ item }}"
    state: absent
  loop: "{{ web_files }}"

- name: 패키지 삭제
  ansible.builtin.dnf:
    name: "{{ package }}"
    state: absent
